### Importing the necessary libraries

In [22]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsRegressor
from sklearn.naive_bayes import GaussianNB

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

import joblib

### Lord The Dataset

In [23]:
df = pd.read_csv('Clean_Churan.csv')

In [24]:
df.head()

,Unnamed: 0,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Splitting the data for input and output

In [25]:
x = df.drop(columns = 'Exited') #Spliting the inputs 
x.head()

y = df['Exited'] #Spliting the output 
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [26]:
x.head()

,Unnamed: 0,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88
1,1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63
4,4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [27]:
num_col = x.columns

In [28]:
x.drop(columns = ['RowNumber', 'CustomerId', 'Surname'],inplace=True)

In [29]:
x.head()

,Unnamed: 0,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

### Splitting the data for the training and tsting

In [30]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2)

In [31]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((7654, 11), (1914, 11), (7654,), (1914,))

### creating the pipline

In [32]:
cat_cols = [
    "Geography",
    "Gender"
]

In [33]:
num_cols = [
    "CreditScore",
    "Age",
    "Tenure",
    "Balance",
    "NumOfProducts",
    "HasCrCard",
    "IsActiveMember",
    "EstimatedSalary"
]

In [34]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_cols),
        ("cat", OneHotEncoder(), cat_cols)
    ]
)

In [35]:
pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", LogisticRegression(class_weight="balanced"))
])

In [36]:
#Training the model 
pipeline.fit(X_train,Y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Geography', 'Gender'])])),
                ('model', LogisticRegression(class_weight='balanced'))])

In [37]:
y_pred = pipeline.predict(X_train)

In [38]:
accuracy = accuracy_score(y_pred,Y_train)
accuracy

0.7202769793571988

In [39]:
joblib.dump(accuracy,"acc_log.pkl")

['acc_log.pkl']

In [40]:
Cust_1 = pd.DataFrame({
    "CreditScore": [400],
    "Geography": ["France"],
    "Gender": ["Male"],
    "Age": [65],
    "Tenure": [5],
    "Balance": [7000],
    "NumOfProducts": [2],
    "HasCrCard": [1],
    "IsActiveMember": [1],
    "EstimatedSalary": [500000]
})

In [41]:
pipeline.predict(Cust_1)

array([1])

In [42]:
pipeline.predict_proba(Cust_1)

array([[0.20951853, 0.79048147]])

In [74]:
joblib.dump(pipeline,"churn_pipeline.pkl")

['churn_pipeline.pkl']

##### Decision Tree Classifier

In [44]:
pipeline_DT = Pipeline([
    ("preprocessing", preprocessor),
    ("model", DecisionTreeClassifier())
])

In [45]:
pipeline_DT.fit(X_train,Y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Geography', 'Gender'])])),
                ('model', DecisionTreeClassifier())])

In [46]:
y_pred_dt = pipeline_DT.predict(X_test)

In [47]:
accuracy_dt_test = accuracy_score(Y_test,y_pred_dt)
accuracy_dt_test

0.7836990595611285

In [48]:
joblib.dump(accuracy_dt_test,"acc_dt.pkl")

['acc_dt.pkl']

In [49]:
joblib.dump(pipeline_DT,"churn_pipeline_DT.pkl")

['churn_pipeline_DT.pkl']

### Random Forest Regressor

In [50]:
pipeline_RF = Pipeline([
    ("preprocessing", preprocessor),
    ("model", RandomForestClassifier(n_estimators=100,random_state=42))
])

In [51]:
pipeline_RF.fit(X_train, Y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Geography', 'Gender'])])),
                ('model', RandomForestClassifier(random_state=42))])

In [52]:
y_pred_rf = pipeline_RF.predict(X_test)

In [53]:
accuracy_rf_test = accuracy_score(Y_test,y_pred_rf)
accuracy_rf_test

0.8646812957157785

In [54]:
joblib.dump(accuracy_rf_test,"acc_rf.pkl")

['acc_rf.pkl']

In [55]:
joblib.dump(pipeline_RF,"churn_pipeline_RF.pkl")

['churn_pipeline_RF.pkl']

### Support Vector Regressor (SVR)

In [56]:
pipeline_SVC = Pipeline([
    ("preprocessing", preprocessor),
    ("model", SVC(
    kernel='rbf',
    C=1.0,
    gamma='scale',
    random_state=42
))
])

In [57]:
pipeline_SVC.fit(X_train, Y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Geography', 'Gender'])])),
                ('model', SVC(random_state=42))])

In [58]:
y_pred_svc = pipeline_SVC.predict(X_test)

In [59]:
accuracy_svc_test = accuracy_score(Y_test,y_pred_svc)
accuracy_svc_test

0.8605015673981191

In [60]:
joblib.dump(accuracy_svc_test,"acc_svc.pkl")

['acc_svc.pkl']

In [61]:
joblib.dump(pipeline_SVC,"churn_pipeline_SVC.pkl")

['churn_pipeline_SVC.pkl']

### K-Nearest Neighbors Regressor

In [62]:
pipeline_KNN = Pipeline([
    ("preprocessing", preprocessor),
    ("model", KNeighborsRegressor(
        n_neighbors=5,
        weights='uniform',
        metric='minkowski',
        p=2
    ))
])

In [63]:
pipeline_KNN.fit(X_train, Y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Geography', 'Gender'])])),
                ('model', KNeighborsRegressor())])

In [64]:
y_pred_knn = pipeline_KNN.predict(X_test)

In [65]:
Y_test = Y_test.astype(int)
y_pred_knn = y_pred_knn.astype(int)

accuracy_knn_test = accuracy_score(Y_test, y_pred_knn)
accuracy_knn_test

0.8160919540229885

In [66]:
joblib.dump(accuracy_knn_test,"acc_knn.pkl")

['acc_knn.pkl']

In [67]:
joblib.dump(pipeline_KNN,"churn_pipeline_KNN.pkl")

['churn_pipeline_KNN.pkl']

### Naive Bayes

In [68]:
pipeline_NB = Pipeline([
    ("preprocessing", preprocessor),
    ("model", GaussianNB())
])

In [69]:
pipeline_NB.fit(X_train,Y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Geography', 'Gender'])])),
                ('model', GaussianNB())])

In [70]:
y_pred_nb = pipeline_NB.predict(X_test)

In [71]:
accuracy_nb_test = accuracy_score(Y_test, y_pred_nb)
accuracy_nb_test

0.835423197492163

In [72]:
joblib.dump(accuracy_nb_test,"acc_nb.pkl")

['acc_nb.pkl']

In [73]:
joblib.dump(pipeline_NB,"churn_pipeline_NB.pkl")

['churn_pipeline_NB.pkl']